// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240116192134_updateTest")]
    partial class updateTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Domain.Model.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TestID");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerID = 1,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = 3,
                            Title = "Strongly Agree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 2,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = 2,
                            Title = "Agree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 3,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = 1,
                            Title = "Slightly Agree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 4,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Neutral",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 5,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = -1,
                            Title = "Slightly Disagree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 6,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = -2,
                            Title = "Disagree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 7,
                            CategoryID = 1,
                            IsPhoto = false,
                            Score = -3,
                            Title = "Strongly Disagree",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 8,
                            CategoryID = 2,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Not at all",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 9,
                            CategoryID = 2,
                            IsPhoto = false,
                            Score = 1,
                            Title = "Several days",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 10,
                            CategoryID = 2,
                            IsPhoto = false,
                            Score = 2,
                            Title = "More than half the days",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 11,
                            CategoryID = 2,
                            IsPhoto = false,
                            Score = 3,
                            Title = "Nearly every day",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 12,
                            CategoryID = 3,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Not at all sure",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 13,
                            CategoryID = 3,
                            IsPhoto = false,
                            Score = 1,
                            Title = "Several days",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 14,
                            CategoryID = 3,
                            IsPhoto = false,
                            Score = 2,
                            Title = "Over half the days",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 15,
                            CategoryID = 3,
                            IsPhoto = false,
                            Score = 3,
                            Title = "Nearly every day",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 16,
                            CategoryID = 4,
                            IsPhoto = true,
                            Score = 1,
                            Title = "Light Blue or Green",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 17,
                            CategoryID = 4,
                            IsPhoto = true,
                            Score = 2,
                            Title = "Dark Blue or Yellow",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 18,
                            CategoryID = 4,
                            IsPhoto = true,
                            Score = 3,
                            Title = "Red or Orange",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 19,
                            CategoryID = 5,
                            IsPhoto = true,
                            Score = 1,
                            Title = "Day",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 20,
                            CategoryID = 5,
                            IsPhoto = true,
                            Score = 2,
                            Title = "Night",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 21,
                            CategoryID = 6,
                            IsPhoto = true,
                            Score = 1,
                            Title = "First Avatar",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 22,
                            CategoryID = 6,
                            IsPhoto = true,
                            Score = 2,
                            Title = "Second Avatar",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 23,
                            CategoryID = 6,
                            IsPhoto = true,
                            Score = 3,
                            Title = "Third Avatar",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 24,
                            CategoryID = 6,
                            IsPhoto = true,
                            Score = 4,
                            Title = "Fourth Avatar",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 25,
                            CategoryID = 7,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Sad Image",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 26,
                            CategoryID = 8,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Joyful Image",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 27,
                            CategoryID = 9,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Next 5 years",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 28,
                            CategoryID = 10,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Next 10 years",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 29,
                            CategoryID = 11,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Past 10 years",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 30,
                            CategoryID = 12,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Today",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 31,
                            CategoryID = 13,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Engaging",
                            Value = 0
                        },
                        new
                        {
                            AnswerID = 32,
                            CategoryID = 14,
                            IsPhoto = false,
                            Score = 0,
                            Title = "Share with us",
                            Value = 0
                        });
                });

            modelBuilder.Entity("Domain.Model.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "MBTI"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "PHQ-9"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "GAD-7"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Additional1"
                        },
                        new
                        {
                            CategoryID = 5,
                            Name = "Additional2"
                        },
                        new
                        {
                            CategoryID = 6,
                            Name = "Additional3"
                        },
                        new
                        {
                            CategoryID = 7,
                            Name = "Additional4"
                        },
                        new
                        {
                            CategoryID = 8,
                            Name = "Additional5"
                        },
                        new
                        {
                            CategoryID = 9,
                            Name = "Additional6"
                        },
                        new
                        {
                            CategoryID = 10,
                            Name = "Additional17"
                        },
                        new
                        {
                            CategoryID = 11,
                            Name = "Additional8"
                        },
                        new
                        {
                            CategoryID = 12,
                            Name = "Additional9"
                        },
                        new
                        {
                            CategoryID = 13,
                            Name = "Additional10"
                        },
                        new
                        {
                            CategoryID = 14,
                            Name = "Additional11"
                        });
                });

            modelBuilder.Entity("Domain.Model.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("TestID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Tests");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Test");

                    b.HasData(
                        new
                        {
                            TestID = 1,
                            CategoryID = 2,
                            Number = 1,
                            Question = "1. Little interest or pleasure in doing things."
                        },
                        new
                        {
                            TestID = 2,
                            CategoryID = 2,
                            Number = 2,
                            Question = "2. Feeling down, depressed, or hopeless."
                        },
                        new
                        {
                            TestID = 3,
                            CategoryID = 2,
                            Number = 3,
                            Question = "3. Trouble falling or staying asleep, or sleeping too much."
                        },
                        new
                        {
                            TestID = 4,
                            CategoryID = 2,
                            Number = 4,
                            Question = "4. Feeling tired or having little energy."
                        },
                        new
                        {
                            TestID = 5,
                            CategoryID = 2,
                            Number = 5,
                            Question = "5. Poor appetite or overeating."
                        },
                        new
                        {
                            TestID = 6,
                            CategoryID = 2,
                            Number = 6,
                            Question = "6. Feeling bad about yourself or that you are a failure or have let yourself or your family down."
                        },
                        new
                        {
                            TestID = 7,
                            CategoryID = 2,
                            Number = 7,
                            Question = "7. Trouble concentrating on things, such as reading the newspaper or watching television."
                        },
                        new
                        {
                            TestID = 8,
                            CategoryID = 2,
                            Number = 8,
                            Question = "8. Moving or speaking so slowly that other people could have noticed. Or the opposite being so fidgety or restless that you have been moving around a lot more than usual."
                        },
                        new
                        {
                            TestID = 9,
                            CategoryID = 2,
                            Number = 9,
                            Question = "9. Thoughts that you would be better off dead, or of hurting yourself in some way."
                        },
                        new
                        {
                            TestID = 10,
                            CategoryID = 3,
                            Number = 1,
                            Question = "1. Feeling nervous, anxious, or on edge."
                        },
                        new
                        {
                            TestID = 11,
                            CategoryID = 3,
                            Number = 2,
                            Question = "2. Not being able to stop or control worrying."
                        },
                        new
                        {
                            TestID = 12,
                            CategoryID = 3,
                            Number = 3,
                            Question = "3. Worrying too much about different things."
                        },
                        new
                        {
                            TestID = 13,
                            CategoryID = 3,
                            Number = 4,
                            Question = "4. Trouble relaxing."
                        },
                        new
                        {
                            TestID = 14,
                            CategoryID = 3,
                            Number = 5,
                            Question = "5. Being so restless that it’s hard to sit still."
                        },
                        new
                        {
                            TestID = 15,
                            CategoryID = 3,
                            Number = 6,
                            Question = "6. Becoming easily annoyed or irritable."
                        },
                        new
                        {
                            TestID = 16,
                            CategoryID = 3,
                            Number = 7,
                            Question = "7. Feeling afraid as if something awful might happen."
                        },
                        new
                        {
                            TestID = 77,
                            CategoryID = 4,
                            Number = 1,
                            Question = "Among these images, which one appeals to you the most?"
                        },
                        new
                        {
                            TestID = 78,
                            CategoryID = 5,
                            Number = 2,
                            Question = "Which one do you prefer?"
                        },
                        new
                        {
                            TestID = 79,
                            CategoryID = 6,
                            Number = 3,
                            Question = "Which of the following images would you like to choose as your profile picture?"
                        },
                        new
                        {
                            TestID = 80,
                            CategoryID = 7,
                            Number = 4,
                            Question = "Please describe the following image briefly."
                        },
                        new
                        {
                            TestID = 81,
                            CategoryID = 8,
                            Number = 5,
                            Question = "Please describe the following image briefly."
                        },
                        new
                        {
                            TestID = 82,
                            CategoryID = 9,
                            Number = 6,
                            Question = "How do you envision yourself in 5 years from now?"
                        },
                        new
                        {
                            TestID = 83,
                            CategoryID = 10,
                            Number = 7,
                            Question = "How do you envision yourself in 10 years from now?"
                        },
                        new
                        {
                            TestID = 84,
                            CategoryID = 11,
                            Number = 8,
                            Question = "How would you describe the past 10 years of yourself?"
                        },
                        new
                        {
                            TestID = 85,
                            CategoryID = 12,
                            Number = 9,
                            Question = "How would you describe your day so far?"
                        },
                        new
                        {
                            TestID = 86,
                            CategoryID = 13,
                            Number = 10,
                            Question = "Would you be interested in engaging with our website to boost your spirits?"
                        },
                        new
                        {
                            TestID = 87,
                            CategoryID = 14,
                            Number = 11,
                            Question = "Do you have any additional comments or thoughts you'd like to share with us?"
                        });
                });

            modelBuilder.Entity("Domain.Model.MBTI", b =>
                {
                    b.HasBaseType("Domain.Model.Test");

                    b.Property<string>("PersonalType")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MBTI");

                    b.HasData(
                        new
                        {
                            TestID = 17,
                            CategoryID = 1,
                            Number = 1,
                            Question = "You regularly make new friends.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 18,
                            CategoryID = 1,
                            Number = 2,
                            Question = "You spend a lot of your free time exploring various random topics that pique your interest.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 19,
                            CategoryID = 1,
                            Number = 3,
                            Question = "Seeing other people cry can easily make you feel like you want to cry too.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 20,
                            CategoryID = 1,
                            Number = 4,
                            Question = "You often make a backup plan for a backup plan.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 21,
                            CategoryID = 1,
                            Number = 5,
                            Question = "You usually stay calm, even under a lot of pressure.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 22,
                            CategoryID = 1,
                            Number = 6,
                            Question = "At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 23,
                            CategoryID = 1,
                            Number = 7,
                            Question = "You prefer to completely finish one project before starting another.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 24,
                            CategoryID = 1,
                            Number = 8,
                            Question = "You are very sentimental.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 25,
                            CategoryID = 1,
                            Number = 9,
                            Question = "You like to use organizing tools like schedules and lists.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 26,
                            CategoryID = 1,
                            Number = 10,
                            Question = "Even a small mistake can cause you to doubt your overall abilities and knowledge.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 27,
                            CategoryID = 1,
                            Number = 11,
                            Question = "You feel comfortable jist walking up to someone you find interesting and striking up a conversation.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 28,
                            CategoryID = 1,
                            Number = 12,
                            Question = "You are not too interested in discussing various interpretations and analyses of creative works.",
                            PersonalType = "SN"
                        },
                        new
                        {
                            TestID = 29,
                            CategoryID = 1,
                            Number = 13,
                            Question = "You are more inclined to follow your head than your heart.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 30,
                            CategoryID = 1,
                            Number = 14,
                            Question = "You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 31,
                            CategoryID = 1,
                            Number = 15,
                            Question = "You rarely worry about whether you make a good impression on people you meet.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 32,
                            CategoryID = 1,
                            Number = 16,
                            Question = "You enjoy participating in group activities.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 33,
                            CategoryID = 1,
                            Number = 17,
                            Question = "You like books and movies that make you come up with your own interpretation of the ending.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 34,
                            CategoryID = 1,
                            Number = 18,
                            Question = "Your happiness comes more from helping others accomplish things than your own accomplishments.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 35,
                            CategoryID = 1,
                            Number = 19,
                            Question = "You are interested in so many things that you find it difficult to choose what to try next.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 36,
                            CategoryID = 1,
                            Number = 20,
                            Question = "You are prone to worrying that things will take a turn for the worse.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 37,
                            CategoryID = 1,
                            Number = 21,
                            Question = "You avoid leadership roles in group settings.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 38,
                            CategoryID = 1,
                            Number = 22,
                            Question = "You are definitely not an artistic type of person.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 39,
                            CategoryID = 1,
                            Number = 23,
                            Question = "You think the world would be a better place if people relied more on rationality and less on their feelings.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 40,
                            CategoryID = 1,
                            Number = 24,
                            Question = "You prefer to do your chores before allowing yourself to relax.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 41,
                            CategoryID = 1,
                            Number = 25,
                            Question = "You enjoy watching people argue.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 42,
                            CategoryID = 1,
                            Number = 26,
                            Question = "You tend to avoid drawing attention to yourself.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 43,
                            CategoryID = 1,
                            Number = 27,
                            Question = "Your mood can change very quickly.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 44,
                            CategoryID = 1,
                            Number = 28,
                            Question = "You lose patience with people who are not as efficient as you.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 45,
                            CategoryID = 1,
                            Number = 29,
                            Question = "You often end up doing things at the last possible moment.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 46,
                            CategoryID = 1,
                            Number = 30,
                            Question = "You have always been fascinated by the question of what, if anything, happens after death.",
                            PersonalType = "SN"
                        },
                        new
                        {
                            TestID = 47,
                            CategoryID = 1,
                            Number = 31,
                            Question = "You usually prefer to be around others rather than on your own.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 48,
                            CategoryID = 1,
                            Number = 32,
                            Question = "You become bored or lose interest when the discussion gets highly theoretical.",
                            PersonalType = "SN"
                        },
                        new
                        {
                            TestID = 49,
                            CategoryID = 1,
                            Number = 33,
                            Question = "You find it easy to empathize with a person whose experiences are very different from yours.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 50,
                            CategoryID = 1,
                            Number = 34,
                            Question = "You usually postpone finalizing decisions for as long as possible.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 51,
                            CategoryID = 1,
                            Number = 35,
                            Question = "You rarely second-guess the choices that you have made.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 52,
                            CategoryID = 1,
                            Number = 36,
                            Question = "After a long and exhausting week, a lively social event is just what you need.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 53,
                            CategoryID = 1,
                            Number = 37,
                            Question = "You enjoy going to art museums.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 54,
                            CategoryID = 1,
                            Number = 38,
                            Question = "You often have a hard time understanding other people’s feelings.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 55,
                            CategoryID = 1,
                            Number = 39,
                            Question = "You like to have a to-do list for each day.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 56,
                            CategoryID = 1,
                            Number = 40,
                            Question = "You rarely feel insecure.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 57,
                            CategoryID = 1,
                            Number = 41,
                            Question = "You avoid making phone calls.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 58,
                            CategoryID = 1,
                            Number = 42,
                            Question = "You often spend a lot of time trying to understand views that are very different from your own.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 59,
                            CategoryID = 1,
                            Number = 43,
                            Question = "In your social circle, you are often the one who contacts your friends and initiates activities.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 60,
                            CategoryID = 1,
                            Number = 44,
                            Question = "If your plans are interrupted, your top priority is to get back on track as soon as possible.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 61,
                            CategoryID = 1,
                            Number = 45,
                            Question = "You are still bothered by mistakes that you made a long time ago.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 62,
                            CategoryID = 1,
                            Number = 46,
                            Question = "You rarely contemplate the reasons for human existence or the meaning of life.",
                            PersonalType = "SN"
                        },
                        new
                        {
                            TestID = 63,
                            CategoryID = 1,
                            Number = 47,
                            Question = "Your emotions control you more than you control them.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 64,
                            CategoryID = 1,
                            Number = 48,
                            Question = "You take great care not to make people look bad, even when it is completely their fault.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 65,
                            CategoryID = 1,
                            Number = 49,
                            Question = "Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 66,
                            CategoryID = 1,
                            Number = 50,
                            Question = "When someone thinks highly of you, you wonder how long it will take them to feel disappointed in you.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 67,
                            CategoryID = 1,
                            Number = 51,
                            Question = "You would love a job that requires you to work alone most of the time.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 68,
                            CategoryID = 1,
                            Number = 52,
                            Question = "You believe that pondering abstract philosophical Question is a waste of time.",
                            PersonalType = "SN"
                        },
                        new
                        {
                            TestID = 69,
                            CategoryID = 1,
                            Number = 53,
                            Question = "You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.",
                            PersonalType = "EI"
                        },
                        new
                        {
                            TestID = 70,
                            CategoryID = 1,
                            Number = 54,
                            Question = "You know at first glance how someone is feeling.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 71,
                            CategoryID = 1,
                            Number = 55,
                            Question = "You often feel overwhelmed.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 72,
                            CategoryID = 1,
                            Number = 56,
                            Question = "You complete things methodically without skipping over any steps.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 73,
                            CategoryID = 1,
                            Number = 57,
                            Question = "You are very intrigued by things labeled as controversial.",
                            PersonalType = "?"
                        },
                        new
                        {
                            TestID = 74,
                            CategoryID = 1,
                            Number = 58,
                            Question = "You would pass along a good opportunity if you thought someone else needed it more.",
                            PersonalType = "TF"
                        },
                        new
                        {
                            TestID = 75,
                            CategoryID = 1,
                            Number = 59,
                            Question = "You struggle with deadlines.",
                            PersonalType = "JP"
                        },
                        new
                        {
                            TestID = 76,
                            CategoryID = 1,
                            Number = 60,
                            Question = "You feel confident that things will work out for you.",
                            PersonalType = "?"
                        });
                });

            modelBuilder.Entity("Domain.Model.Answer", b =>
                {
                    b.HasOne("Domain.Model.Category", "Category")
                        .WithMany("Answers")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.Test", null)
                        .WithMany("Answers")
                        .HasForeignKey("TestID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Model.Test", b =>
                {
                    b.HasOne("Domain.Model.Category", "Category")
                        .WithMany("Tests")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Model.Category", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Domain.Model.Test", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
